<?php
require_once __DIR__.'/../config.php';
$pageTitle='Udaipur Solo Trip Gallery | Swiggy Wala';
$pageDescription='Explore a real Swiggy Wala Udaipur solo-trip gallery featuring camel safari, Gangaur Ghat, Bagore Ki Haveli, local auto rides, cafes and heritage moments.';
$canonical=SITE_URL.'/gallery/';
$extraStylesheets=['/assets/css/travel-story.css'];
$pageSchema=['@context'=>'https://schema.org','@type'=>'ImageGallery','name'=>'Swiggy Wala Udaipur Solo Trip Gallery','description'=>$pageDescription,'url'=>$canonical,'about'=>['@type'=>'Place','name'=>'Udaipur, Rajasthan']];
include __DIR__.'/../includes/header.php';
?>
<main><section class="page-hero"><div class="container"><div class="breadcrumb"><a href="/">Home</a> / Gallery</div><span class="eyebrow">Featured client journey</span><h1>Udaipur Solo Trip Gallery</h1><p>Real moments from a 3-day solo Udaipur journey with Swiggy Wala — camel experience, local streets, Gangaur Ghat, Bagore Ki Haveli, cafes and heritage spaces.</p></div></section>
<section class="story-section"><div class="container gallery-feature"><div><span class="eyebrow">Top featured story</span><h2 class="content-title">3 days, solo in Udaipur.</h2><p>This gallery is connected to a real traveller journey organised with Swiggy Wala. The camel safari was a special activity within the larger trip, while the rest of the experience focused on Udaipur’s local movement, heritage, lakefront atmosphere, food and slower travel moments.</p><div class="gallery-caption-list"><div class="gallery-caption"><strong>🐪 Camel Safari / Camel Experience</strong><small>Special activity within the main 3-day solo trip.</small></div><div class="gallery-caption"><strong>🛺 Udaipur Local Auto Ride</strong><small>Exploring streets and neighbourhoods at a flexible pace.</small></div><div class="gallery-caption"><strong>🌅 Gangaur Ghat</strong><small>Sunset, lakefront views and local atmosphere.</small></div><div class="gallery-caption"><strong>🏛️ Bagore Ki Haveli Area</strong><small>Heritage surroundings and an evening old-city experience.</small></div><div class="gallery-caption"><strong>☕ Quala Cafe</strong><small>Food, colour and distinctive interiors during the journey.</small></div><div class="gallery-caption"><strong>🤍 Jagat Niwas Palace</strong><small>White heritage architecture and a calm morning experience.</small></div></div><div class="story-links"><a class="btn" href="/stories/udaipur-solo-trip/">Read Full Trip Story</a><a class="btn btn-outline" href="/blogs/3-day-solo-udaipur-trip-swiggywala/">Read Travel Blog</a></div></div><div class="ig-card"><h2 style="font:700 28px 'Playfair Display';margin:4px 0 14px">Original traveller photo carousel</h2><blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/p/DW8I6pJDI1o/" data-instgrm-version="14" style="background:#fff;border:0;margin:0;max-width:540px;width:100%"></blockquote><p class="social-proof">Traveller: <a target="_blank" rel="noopener" href="https://www.instagram.com/debchandrima_official/">@debchandrima_official</a></p><div class="gallery-note">The public Instagram carousel is embedded here as the source gallery for this featured client story.</div></div></div></section>
<section class="story-section alt"><div class="container"><div class="story-intro"><span class="eyebrow">More journeys coming</span><h2>Real Swiggy Wala travel stories.</h2><p>As more client journeys are completed, this gallery can grow into destination-wise collections for Jaipur, Udaipur, Jaisalmer, Jodhpur and other Rajasthan experiences.</p></div></div></section></main>
<script async src="https://www.instagram.com/embed.js"></script>
<?php include __DIR__.'/../includes/footer.php'; ?>
