<?php
require_once __DIR__.'/../config.php';$blogs=require __DIR__.'/../data/blogs.php';
if(!isset($blogSlug,$blogs[$blogSlug])){http_response_code(404);exit('Guide not found');}$b=$blogs[$blogSlug];
$pageTitle=$b['title'].' | Swiggy Wala';$pageDescription=$b['description'];$canonical=SITE_URL.'/blog/'.$blogSlug.'.php';
$ogType='article';$ogImage=SITE_URL.'/assets/images/blog/'.basename($b['image']);include __DIR__.'/header.php';
?>
<main><section class="page-hero"><div class="container"><div class="breadcrumb"><a href="/">Home</a> / <a href="/blog.php">Travel Guides</a> / <?= e($b['keyword']) ?></div><h1><?= e($b['title']) ?></h1><div class="article-meta"><span>Updated <?= date('j M Y',strtotime($b['date'])) ?></span><span><?= e($b['read']) ?></span></div></div></section><section class="section"><div class="container article-wrap"><article class="article"><div class="article-hero" style="background-image:url('<?= e($b['image']) ?>')"><span class="sr-only"><?= e($b['title']) ?></span></div><p class="article-lead"><?= e($b['intro']) ?></p>
<?php if(!empty($b['gallery'])):?><div class="article-gallery" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin:24px 0;"><?php foreach($b['gallery'] as $g):?><figure style="margin:0"><img src="<?= e($g['src']) ?>" alt="<?= e($g['alt']) ?>" loading="lazy" width="1200" height="675" style="width:100%;height:auto;border-radius:16px;display:block"><figcaption style="font-size:.88rem;margin-top:8px;opacity:.78"><?= e($g['caption']) ?></figcaption></figure><?php endforeach;?></div><?php endif;?>
<?php foreach($b['sections'] as $s):?><h2><?= e($s[0]) ?></h2><p><?= e($s[1]) ?></p><?php endforeach;?>
<?php if(!empty($b['faqs'])):?><h2>Frequently asked questions</h2><div class="article-faq"><?php foreach($b['faqs'] as $f):?><div class="faq-item"><h3><?= e($f[0]) ?></h3><p><?= e($f[1]) ?></p></div><?php endforeach;?></div><?php endif;?>
<h2>Plan your trip with Swiggy Wala</h2><p>Tell us your travel dates, number of travellers, starting city, hotel preference and must-see experiences. We can turn those details into a personalised Rajasthan itinerary and current quotation. Attraction hours, prices, road conditions and local rules can change, so verify them close to travel.</p></article><aside class="sidebar"><div class="sidebar-box"><h3>Plan this journey</h3><p>Get a custom route for your dates and travel style.</p><a class="btn" href="<?= e(wa_link('Hello Swiggy Wala, I read your guide: '.$b['title'].'. Please plan my trip.')) ?>"><?= wa_icon() ?>Ask on WhatsApp</a></div><div class="sidebar-box"><h3>Related planning</h3><a href="/destinations.php">Explore destinations</a><a href="/packages.php">View tour ideas</a><a href="/blog.php">More travel guides</a><a href="/contact.php">Send trip details</a></div></aside></div></section></main>
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'BlogPosting','headline'=>$b['title'],'description'=>$b['description'],'image'=>$ogImage,'datePublished'=>$b['date'],'dateModified'=>$b['date'],'author'=>['@type'=>'Organization','name'=>SITE_NAME],'publisher'=>['@type'=>'Organization','name'=>SITE_NAME,'logo'=>['@type'=>'ImageObject','url'=>SITE_URL.'/assets/images/brand/logo-horizontal-1600.png']],'mainEntityOfPage'=>$canonical],JSON_UNESCAPED_SLASHES) ?></script>
<?php if(!empty($b['faqs'])):?><script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>array_map(fn($f)=>['@type'=>'Question','name'=>$f[0],'acceptedAnswer'=>['@type'=>'Answer','text'=>$f[1]]],$b['faqs'])],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) ?></script><?php endif;?>
<?php include __DIR__.'/footer.php';?>
