<?php
require_once __DIR__.'/../config.php';$groups=require __DIR__.'/../data/services.php';$service=null;$group=null;$groupSlug='';
foreach($groups as $gs=>$g){foreach($g['items'] as $item){if(isset($serviceSlug)&&$item[0]===$serviceSlug){$service=$item;$group=$g;$groupSlug=$gs;break 2;}}}
if(!$service){http_response_code(404);exit('Service not found');}
[$slug,$name,$keyword,$summary]=$service;
$isSelfDrive=$slug==='self-drive-car-rental';
$pageTitle=$name.' in Jaipur & Rajasthan | Swiggy Wala';
$pageDescription=$summary.' Ask Swiggy Wala for availability and a customised plan.';
$canonical=SITE_URL.'/services/'.$slug.'/';
include __DIR__.'/header.php';
$benefits=$groupSlug==='packages'?['Route adapted to your dates','Stay and vehicle options','Balanced sightseeing pace','Clear quotation before booking']:($groupSlug==='specialized'?['One group coordination point','Purpose-based itinerary','Transport options by group size','Flexible sightseeing choices']:($groupSlug==='travel-services'?['Advance pickup planning','Vehicle options by requirement','Clear route and timing','Easy WhatsApp coordination']:['Custom route and duration','Local destination knowledge','Flexible private or group format','Clear inclusions and options']));
?>
<main><section class="page-hero service-detail-hero"><div class="container"><div class="breadcrumb"><a href="/">Home</a> / <a href="/services.php">Services</a> / <?= e($name) ?></div><span class="eyebrow"><?= e($group['label']) ?></span><h1><?= e($name) ?> in Jaipur & Rajasthan</h1><p><?= e($summary) ?></p><div class="hero-actions"><a class="btn" href="<?= e(wa_link('Hello Swiggy Wala, I need details about '.$name.'.')) ?>" target="_blank" rel="noopener"><?= wa_icon() ?>Check Availability</a><a class="btn btn-outline" href="tel:<?= PHONE_TEL ?>">Call <?= PHONE_DISPLAY ?></a></div></div></section>
<section class="section"><div class="container service-intro-grid"><article><span class="eyebrow">Planned around you</span><h2 class="content-title">A clearer way to arrange <?= e(strtolower($name)) ?>.</h2><p><?= e($summary) ?> Swiggy Wala begins with your travel date, group size, starting location and preferred pace. We then identify a practical route and the options that genuinely suit the request.</p><p>Instead of forcing every traveller into the same schedule, we can adjust pickup time, sightseeing priorities, breaks and trip duration. Final availability, pricing and inclusions are confirmed in writing before booking.</p><?php if($isSelfDrive):?><div class="service-note"><strong>Secondary partner service:</strong> Self-drive cars are not our primary business. Requests may be referred to a verified rental partner and remain subject to driving-licence verification, security deposit, vehicle policy, age criteria and availability.</div><?php endif;?></article><aside class="service-summary"><h3>Service highlights</h3><ul class="check-list"><?php foreach($benefits as $benefit):?><li><?= e($benefit) ?></li><?php endforeach;?></ul><a class="btn" href="/contact.php">Request a Custom Plan</a></aside></div></section>
<?php if(in_array($slug,['campus-tours','educational-tours','school-college-tours'],true)): ?>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Jaipur education visit resource</span><h2>Research colleges before planning campus visits.</h2></div><p>Students and families arranging Jaipur campus visits can use <a href="https://collegeinjaipur.com/" target="_blank" rel="noopener">College in Jaipur</a> to research colleges and course categories before finalising a travel route.</p></div></div></section>
<?php endif; ?>
<section class="section section-soft"><div class="container"><div class="section-head"><div><span class="eyebrow">What we need</span><h2>Share five trip details.</h2></div><p>Accurate details help us suggest a useful plan instead of a generic package.</p></div><div class="process"><div class="step"><b>01</b><h3>Travel date</h3><p>Your preferred date and flexibility.</p></div><div class="step"><b>02</b><h3>Traveller count</h3><p>Adults, children and group needs.</p></div><div class="step"><b>03</b><h3>Pickup point</h3><p>Hotel, airport, station or city.</p></div><div class="step"><b>04</b><h3>Preferences</h3><p>Budget, pace and must-see places.</p></div></div></div></section>
<section class="section"><div class="container faq-wrap"><span class="eyebrow">Common questions</span><h2 class="content-title"><?= e($name) ?> FAQs</h2><details open><summary>Can this service be customised?</summary><p>Yes. Timing, duration, route and supporting arrangements can be adapted to your requirements, subject to availability and local operating conditions.</p></details><details><summary>How is the price calculated?</summary><p>Pricing depends on travel date, group size, duration, route, vehicle or experience category and the inclusions you select. We provide a current quotation after receiving these details.</p></details><details><summary>What should I confirm before payment?</summary><p>Review the final itinerary, inclusions, exclusions, cancellation terms, pickup details, supplier conditions and payment schedule. Ask for clarification whenever an item is not explicit.</p></details><details><summary>Are attraction timings and tickets included?</summary><p>Only when the written quotation says so. Attraction hours, ticket prices, permissions and weather rules can change, so they are rechecked near the travel date.</p></details></div></section>
<section class="section section-soft"><div class="container split compact-split"><div><span class="eyebrow">Related options</span><h2 class="content-title">Build a complete Rajasthan plan.</h2><p>Combine <?= e(strtolower($name)) ?> with destination stays, guided sightseeing, transfers and custom day-wise planning.</p></div><div class="related-links"><a href="/packages.php">Tour packages <b>→</b></a><a href="/destinations.php">Rajasthan destinations <b>→</b></a><a href="/blogs/">Travel guides <b>→</b></a><a href="/services.php">All services <b>→</b></a></div></div></section></main>
<script type="application/ld+json"><?= json_encode(['@context'=>'https://schema.org','@type'=>'Service','name'=>$name,'description'=>$pageDescription,'provider'=>['@type'=>'TravelAgency','name'=>SITE_NAME,'url'=>SITE_URL,'telephone'=>PHONE_DISPLAY],'areaServed'=>['@type'=>'State','name'=>'Rajasthan'],'url'=>$canonical],JSON_UNESCAPED_SLASHES) ?></script>
<?php include __DIR__.'/footer.php';?>
